### ISSUE TITLE
Exception of XAudio2

### ISSUE THREAD

**Issue by jhdevelp** [EvergineTeam/Feedback#113]
Hello guys,

I have following exception during starting application.

`Unhandled exception. SharpGen.Runtime.SharpGenException: HRESULT: [0x88960001]
   at SharpGen.Runtime.Result.ThrowFailureException()
   at SharpGen.Runtime.Result.CheckError()
 at Vortice.XAudio2.XAudio2Native.XAudio2Create(Int32 flags, ProcessorSpecifier processorSpecifier)
 at Vortice.XAudio2.IXAudio2..ctor(ProcessorSpecifier processorSpecifier, Boolean registerCallback)
 at Vortice.XAudio2.XAudio2.XAudio2Create(ProcessorSpecifier processorSpecifier, Boolean registerCallback)
at Evergine.XAudio2.XAudioDevice..ctor() in C:\azp\agent\_work\2\s\src\Engine\Audio\Evergine.XAudio2\XAudioDevice.cs:line 40
....
`

I have same problem when I creating new project or use sample.

I can remove code of from VS in order to prevent exception
`            
//var xaudio = new Evergine.XAudio2.XAudioDevice();
 //application.Container.RegisterInstance(xaudio)
;`

but It will not fix editor error. 

![editor](https://user-images.githubusercontent.com/98220167/150641073-79909b20-63e7-4790-9630-7e9503ce2d58.png)

![vs_fu](https://user-images.githubusercontent.com/98220167/150641615-d0d99aa0-da29-4ca8-b750-8a81e0558915.png)

I've tried
```

2022.1.22.1-nightly
2021.11.17.2-preview
```

DX11 and DX12 app result is same.

**Comment by jhdevelp** [comment]
I have Zbook and there is a another guy who have similar problem.

![hw_spec](https://user-images.githubusercontent.com/98220167/150641316-a29ffb78-038c-4e63-b757-00c5f2020dbe.png)

**Comment by emepetres** [comment]
@jhdevelp thank you for your report, we'll check whenever possible. If you need a quick resolution, please contact our [priority support](https://evergine.com/priority-support/).

**Comment by jhdevelp** [comment]
> This was known bug and fixed with one of the latest beta release, Evergine probably need to target 2.1.1-beta9 or you can reference [2.1.1-beta9](https://www.nuget.org/packages/Vortice.XAudio2/2.1.1-beta9)

Will you integrate new version of XAudio into Evergine, in order to make it working ?

**Comment by jcant0n** [comment]
Thank you for taking the time to report this issue. We are closing it due to extended inactivity. If you believe this issue is still relevant, please feel free to reopen it and we will be happy to revisit it. Thank you for your understanding and for helping us improve Evergine.
