### ISSUE TITLE
Error when running project with webgl 2

### ISSUE THREAD

**Issue by madamc** [EvergineTeam/Feedback#131]
I am able to successfully build my project with Evergine 2022.2.16.4 for Windows. I'm not certain whether I'm performing build steps for WebGL 2 properly.

At first I was experiencing the same issue as identified in https://github.com/EvergineTeam/Feedback/issues/110, but after installing the wasm-tools I was able to build successfully. However, when I run the project and attempt to hit the web page that is served up. I see the loading screen, and then a dark gray page loads and my app doesn't load. Below is the stack trace I get:
`Unhandled Exception:
System.Exception: Workaround exception to leverage the actual one, not the wrong Delegate-related one
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WaveEngine.Bindings.OpenGL.GL.glDrawElementsInstancedBaseVertex(PrimitiveType mode, Int32 count, DrawElementsType type, Void* indices, Int32 instancecount, Int32 basevertex)
   at Evergine.OpenGL.GLDrawIndexedInstancedCommand.Execute(GLGraphicsContext context)
   at Evergine.OpenGL.CommandCollection.ExecuteAllCommands(GLGraphicsContext context)
   at Evergine.OpenGL.GLCommandBuffer.Execute(GLGraphicsContext context)
   at Evergine.OpenGL.GLCommandQueue.Submit()
   at Evergine.Framework.Services.GraphicsPresenter.Present()
   at Evergine.Framework.Application.DrawFrame(TimeSpan gameTime)
   at MyEvergineProjectForWeb.Web.Program.<>c__DisplayClass5_0.<Run>b__1() in C:\Evergine\MyFirstEvergineProject\MyEvergineProjectForWeb\MyEvergineProjectForWeb.Web\Program.cs:line 61
   at Evergine.Web.WebWindowsSystem.Loop(Double ellapsedMilliseconds)
   --- End of inner exception stack trace ---
   at Evergine.Web.WebWindowsSystem.Loop(Double ellapsedMilliseconds)
   at Evergine.Web.WebAssembly.InvokeRequestAnimationFrameCallback(Double d)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
Uncaught Error: System.Exception: Workaround exception to leverage the actual one, not the wrong Delegate-related one
 ---> System.NullReferenceException: Object reference not set to an instance of an object.WebSocket failed to connect.
The thread 0xa538 has exited with code 0 (0x0).`

are there other steps necessary to follow when building for webgl2?

**Comment by madamc** [comment]
[MyEvergineProjectForWeb.zip](https://github.com/EvergineTeam/Feedback/files/8544038/MyEvergineProjectForWeb.zip)

attaching the project. Builds and runs successfully for windows. Builds successfully for Webgl 2 but runs with errors.

**Comment by emepetres** [comment]
Hi @madamc , thank you for your report. We've added it to our bug roadmap and we will take a look as soon as possible. I let you as well a [link to our documentation](https://docs.evergine.com/2022.2.16/manual/platforms/web/index.html) which may could help.

Finally, If you need faster resolution, we provide priority support for our customers: https://evergine.com/priority-support/

**Comment by madamc** [comment]
Thank you @emepetres. Those instructions in the wiki link you posted were helpful and clear for describing what to do. Unfortunately, I still receive the same error as described above, with the addition of this one shown in the browser console:

> Uncaught TypeError: Cannot read properties of undefined (reading 'call_static_method')
>     at Program.invoke (evergine.js:216:24)
>     at Program.UpdateCanvasSize (evergine.js:213:14)
>     at App.resizeAppSize (evergine.js:26:22)

**Comment by madamc** [comment]
After further troubleshooting, it appears this is only an issue when trying to use the Camera2D object. If I default to a camera3D object, everything renders and runs as expected. When just trying to us a Camera2D, it's as if it is being ignored. Is there a certain configuration the Camera2D has to have in order to work with webgl, or is it not compatible?

**Comment by emepetres** [comment]
Hi @madamc , that's an interesting finding, let us look into it and study what could be wrong here.

**Comment by jcant0n** [comment]
Thank you for taking the time to report this issue. We are closing it due to extended inactivity. If you believe this issue is still relevant, please feel free to reopen it and we will be happy to revisit it. Thank you for your understanding and for helping us improve Evergine.
