### ISSUE TITLE
2022.2.16.5 WPFSurface NullException: {"Value cannot be null. (Parameter 'v')"}

### ISSUE THREAD

**Issue by adamthole** [EvergineTeam/Feedback#132]
I upgraded my project to 2022.2.16.5 and I started receiving a null exception when creating the WPFSurface.  I then tried the AutomotiveDemo and ran into the same issue.  Here is the stack trace:

```
   at System.Windows.PresentationSource.CriticalFromVisual(DependencyObject v, Boolean enable2DTo3DTransition)
   at System.Windows.PresentationSource.FromVisual(Visual visual)
   at Evergine.WPF.WPFSurface.GetDPI()
   at Evergine.WPF.WPFSurface..ctor(UInt32 width, UInt32 height)
   at AutomotiveDemo.WPF.MainWindow.LoadEvergineControl() in C:\Users\adamt\Downloads\Automotive-Demo-master\AutomotiveDemo.WPF\MainWindow.xaml.cs:line 45
   at AutomotiveDemo.WPF.MainWindow..ctor() in C:\Users\adamt\Downloads\Automotive-Demo-master\AutomotiveDemo.WPF\MainWindow.xaml.cs:line 33
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

**Comment by emepetres** [comment]
Thank you @adamthole for your report, indeed we introduced the bug, sorry for that. We are working on it and we will publish a fix a few days.

**Comment by emepetres** [comment]
Hi @adamthole , we have released a new minor version with this issue fixed, please check it out. I'm closing the issue, feel free to reopen if you need it.

**Comment by adamthole** [comment]
I just updated to 2022.2.16.6 and it is working well, thanks! Do you publish release notes with new releases?  If so, where could I find those?  Thanks!

**Comment by emepetres** [comment]
Hi @adamthole, we are not currently publishing release notes for minor versions, but is something we want to start doing in the near future.

Minor versions are only focused on bug fixing so no breaking changes nor new functionality is added.
