### ISSUE TITLE
Issues building projects targeting HTML5

### ISSUE THREAD

**Issue by NinovanderMark** [EvergineTeam/Feedback#160]
Having only recently found out about Evergine, I wanted to try out the HTML5 publishing functionality. I used the launcher to create a new Project, including the HTML5 target. Once finished I opened it in Visual Studio and attempted to build the <Project>.Web project, however the browser console gives me the following error:
```
Uncaught (in promise) ReferenceError: areAllAssetsLoaded is not defined
    at App.waitAndRun (evergine.js:38:9)
    at App.startEvergine (evergine.js:30:14)
    at (index):60:13
```
For some reason there is no implementation for this function, although I can see the `declare` in `types/evergine.d.ts`.

As my project has no assets, I figured I'd work around it by commenting out this check, and having it run the application immediately, which results in the following error:
```
WARNING: function window._evergine_EGL(): Cannot read properties of undefined (reading 'contextAttributes')
blazor.webassembly.js:1 TypeError: Cannot read properties of undefined (reading 'contextAttributes')
blazor.webassembly.js:1     at _evergine_EGL (https://localhost:5001/evergine.js:210:16)
blazor.webassembly.js:1     at Object.invokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3214)
blazor.webassembly.js:1     at Object.Rt [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:59803)
blazor.webassembly.js:1     at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.6.0.13.cryt2i35dx.js:1:195300)
blazor.webassembly.js:1     at wasm://wasm/00971d3e:wasm-function[219]:0x1a492
blazor.webassembly.js:1     at wasm://wasm/00971d3e:wasm-function[167]:0xce60
...
```
Looking at the trace I can see it breaks because it tries accessing `window.EGL.contextAttributes`, but there's no `window.EGL` at all.

It kind of looks like there are some pieces missing from the bundle, but these would probably come in by Blazor pulling them from the Evergine packages, which is a mechanism I'm not very familiar with yet.

Is this a known issue, and is there some way to fix or work around it?

**Comment by NinovanderMark** [comment]
Thank you for the help! Yes, I did not have the WebAssembly build tools installed on this machine, very silly of me.

Now it works like a charm. Very excited about getting to work with this. 😁
