### ISSUE TITLE
Clicking the plus button to add component crashed editor.

### ISSUE THREAD

**Issue by ericcrozier** [EvergineTeam/Feedback#170]
Hey there,

I ran into this today, where the + button kills the editor. Happens every time I click it. It does not happen for any other type of + button, only Component. Changing versions did not help ( I am on latest). Restarting PC did not help. Looks like a index out of range, possibly bad data got saved?

Would appreciate any assistance, thanks!

```
2023-10-03 22:22:09 [Error] [Evergine.Editor.WPF.App] Application exception DispatcherOnUnhandledException.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at Evergine.Editor.WPF.Dialogs.TypeSelector.TypeItem..ctor(String category, String value) in D:\a\Engine\Engine\src\Tools\Editor\Evergine.Editor.WPF\Dialogs\TypeSelector.xaml.cs:line 224
   at Evergine.Editor.WPF.Services.WPFDialogService.<>c__DisplayClass10_0.<ShowTypesSelectorDialog>b__1(String y) in D:\a\Engine\Engine\src\Tools\Editor\Evergine.Editor.WPF\Services\WPFDialogService.cs:line 126
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Evergine.Editor.WPF.Services.WPFDialogService.ShowTypesSelectorDialog(Dictionary`2 availableTypes, TypeSelectorConfiguration configuration) in D:\a\Engine\Engine\src\Tools\Editor\Evergine.Editor.WPF\Services\WPFDialogService.cs:line 123
   at Evergine.Editor.ViewModels.EntityDetailsViewModel.AddComponent() in D:\a\Engine\Engine\src\Tools\Editor\Evergine.Editor\ViewModels\Viewers\Scene\EntityDetailsViewModel.cs:line 208
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by ericcrozier** [comment]
Found the problem, it was caused by a class inheriting from the wrong parent. Specifically, it inheriting from Component caused it to fail. The issue is now resolved.

**Comment by ericcrozier** [comment]
Found the problem, it was caused by a class inheriting from the wrong parent. Specifically, it inheriting from Component caused it to fail. The issue is now resolved.
