### ISSUE TITLE
Directx12 unhandled exception

### ISSUE THREAD

**Issue by Eelos5** [EvergineTeam/Feedback#199]
Hi,

I'm trying to create my first maui project, but i keep getting an exception. At home i have no problems, but my work computer keeps giving exceptions. I'm unable to find the .cs files, so i'm not sure which object reference is not set. Please help?

2024-06-10 08:26:56 [Information] [Evergine.Editor.Services.BuildService]   MauiTest -> E:\Evergine\projects\MauiTest\.evergine\MauiTest.Windows\Build\temp\1icdgerq.axq\bin\MauiTest.dll
2024-06-10 08:26:56 [Information] [Evergine.Editor.Services.BuildService]   MauiTest.Editor -> E:\Evergine\projects\MauiTest\.evergine\MauiTest.Windows\Build\temp\1icdgerq.axq\bin\MauiTest.Editor.dll
2024-06-10 08:27:01 [Error] [Evergine.Runner.Editor.RunnerClient] Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
2024-06-10 08:27:01 [Error] [Evergine.Runner.Editor.RunnerClient]    at Evergine.DirectX12.DX12GraphicsContext.CreateDeviceInternal() in D:\a\Engine\Engine\src\Engine\Rendering\Evergine.DirectX12\DX12GraphicsContext.cs:line 189
2024-06-10 08:27:01 [Error] [Evergine.Runner.Editor.RunnerClient]    at Evergine.Common.Graphics.GraphicsContext.CreateDevice(ValidationLayer validationLayer) in D:\a\Engine\Engine\src\Engine\Common\Evergine.Common\Graphics\GraphicsContext.cs:line 120
2024-06-10 08:27:01 [Error] [Evergine.Runner.Editor.RunnerClient]    at Evergine.Runner.Game.Run(CancellationToken cancellationToken) in D:\a\Engine\Engine\src\Tools\Editor\Evergine.Runner\Game.cs:line 141
2024-06-10 08:27:01 [Error] [Evergine.Runner.Editor.RunnerClient]    at Evergine.Runner.Program.Main(String[] args) in D:\a\Engine\Engine\src\Tools\Editor\Evergine.Runner\Program.cs:line 57
2024-06-10 08:27:09 [Error] [Evergine.Editor.Services.ProjectService] The project has some errors that prevents it to be executed, check the log and reload the project when they are fixed.
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Stream removed", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1718000829.229000000","description":"Error received from peer ipv6:[::1]:63540","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1070,"grpc_message":"Stream removed","grpc_status":2}")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
   at Evergine.Editor.Services.RunnerCommunicationService.Start(ProjectData projectData, CancellationToken cancellationToken) in D:\a\Engine\Engine\src\Tools\Editor\Evergine.Editor\Services\RunnerCommunicationService.cs:line 119
   at Evergine.Editor.Services.ProjectService.InnerStart(CancellationTokenSource cancellationToken) in D:\a\Engine\Engine\src\Tools\Editor\Evergine.Editor\Services\ProjectService.cs:line 395

**Comment by danielcaceresm** [comment]
Hi @Eelos5, 

Apologies for the delayed response.

It appears that you are using DirectX12 as the graphics backend in the Evergine Studio, which for some reason is not working. Could you try switching to DirectX11? 

**Changing the Graphics Backend to DirectX11:**

1. **Modify the `user.config` File:**
   - Navigate to the Evergine Studio's configuration file located at `%LocalAppData%\Evergine\Editor\user.config`.
   - Open the `user.config` file using a text editor.
   - Locate the setting that specifies the graphics backend (e.g., "Backend": "DirectX12"`).
   - Change the value to `DirectX11`:
     ```json
     "Backend": "DirectX11"
     ```
   - Save the changes and close the editor.

2. **Restart Evergine Studio** 

As this issue has been inactive for a while, we plan to close it in a few days if we don't hear back from you. Please let us know if the latest version resolves your concerns or if you need further assistance.

Thank you for your understanding.
