### ISSUE TITLE
SharpDXException when opening wave new editor project 

### ISSUE THREAD

**Issue by MikeCheel** [EvergineTeam/Feedback#38]
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient] Unhandled exception. SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient] 
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at SharpDX.Result.CheckError()
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at SharpDX.Direct3D11.Device5.CreateFence(Int64 initialValue, FenceFlags flags, Guid returnedInterface, Fence fenceOut)
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at SharpDX.Direct3D11.Fence..ctor(Device5 device, Int64 initialValue, FenceFlags flags)
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.DirectX11.DX11CommandQueue..ctor(DX11GraphicsContext graphicsContext) in C:\agent\_work\3\s\src\Engine\Rendering\WaveEngine.DirectX11\DX11CommandQueue.cs:line 53
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.DirectX11.DX11ResourceFactory.CreateCommandQueueInternal(CommandQueueType queueType) in C:\agent\_work\3\s\src\Engine\Rendering\WaveEngine.DirectX11\DX11ResourceFactory.cs:line 30
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.Common.Graphics.ResourceFactory.CreateCommandQueue(CommandQueueType queueType) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Common\Graphics\ResourceFactory.cs:line 27
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.Framework.Services.GraphicsPresenter.OnAttached() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Framework\Services\GraphicsPresenter.cs:line 98
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.Framework.AttachableObject.Attach() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Framework\AttachableObject.cs:line 176
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.Framework.Services.ServiceInterceptor.InitializeServices() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Framework\Services\ServiceInterceptor.cs:line 103
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.Framework.Application.Initialize() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Framework\Application.cs:line 114
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.Runner.Game.Run(CancellationToken cancellationToken) in C:\agent\_work\3\s\src\Tools\Editor\WaveEngine.Runner\Game.cs:line 126
2020-12-01 19:01:51 [Error] [WaveEngine.Runner.Editor.RunnerClient]    at WaveEngine.Runner.Program.Main(String[] args) in C:\agent\_work\3\s\src\Tools\Editor\WaveEngine.Runner\Program.cs:line 57
2020-12-01 19:02:24 [Error] [WaveEngine.Editor.Services.ProjectService] The project has some errors that prevents it to be executed, check the log and reload the project when they are fixed.
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Stream removed", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1606867344.204000000","description":"Error received from peer ipv6:[::1]:58389","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1062,"grpc_message":"Stream removed","grpc_status":2}")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
   at WaveEngine.Editor.Services.RunnerCommunicationService.Start(ProjectData projectData, CancellationToken cancellationToken) in C:\agent\_work\3\s\src\Tools\Editor\WaveEngine.Editor\Services\RunnerCommunicationService.cs:line 116
   at WaveEngine.Editor.Services.ProjectService.InnerStart(CancellationTokenSource cancellationToken) in C:\agent\_work\3\s\src\Tools\Editor\WaveEngine.Editor\Services\ProjectService.cs:line 373

**Comment by MikeCheel** [comment]
I just created a new project and opened it. I installed the prerequisites listed.

**Comment by jcant0n** [comment]
Great!

So, can you close this issue?

**Comment by MikeCheel** [comment]
I mean I installed the prerequisites and this happens right as wave editor
is loading. I can't get it to get past this error.

**Comment by danielcaceresm** [comment]
Thanks you for reporting the issue.

Can you provide more information about your environment (OS and Visual Studio versions, CPU, GPU, ...)?

**Comment by MikeCheel** [comment]
Pulled from dxdiag:

Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
      System Manufacturer: FUJITSU
             System Model: LIFEBOOK T902
                     BIOS: Version 2.08 (type: UEFI)
                Processor: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 CPUs), ~2.6GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8036MB RAM
                Page File: 8660MB used, 1359MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 120 DPI (125 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported

           Card name: Intel(R) HD Graphics 4000
        Manufacturer: Intel Corporation
           Chip type: Intel(R) HD Graphics Family

**Comment by danielcaceresm** [comment]
Hi @MikelCheel,

For some reason, DirectX 11.4 that contains support for Fences is not working.
Can you check [this utility](https://github.com/microsoft/DxCapsViewer/wiki) and confirm that you have support for DirectX 11.4 (specifically the "Driver Concurrent Creates" feature)?

![image](https://user-images.githubusercontent.com/5016114/101881618-f534aa00-3b94-11eb-98c8-ae1a5cf067f8.png)

**Comment by Shadow4walker** [comment]
from here [#41](https://github.com/WaveEngine/Feedback/issues/41) same issue 
![ScreenShot_20201212175035](https://user-images.githubusercontent.com/43580244/101988503-a117eb80-3ca2-11eb-92d3-fe9e502b4bee.png)
so just for clarify: our users who doesn't have this Feature saying yes can't running our apps which created by WaveEngine?

**Comment by danielcaceresm** [comment]
Hi @Shadow4walker @MikeCheel,

We have released a new preview that does not use Fences, and DirectX 11.4 is not a requisite.

Can you test the new release?

Thanks.

**Comment by MikeCheel** [comment]
I created a new project but when I loaded it it just hung at determining
projects to restore. I then closed it and reopened the project that it had
created and after a minute it appears to be coming up now.

Thanks for help.

**Comment by Shadow4walker** [comment]
thanks for the update on this @danielcaceresm 
so I've started a new project Targeted only DirectX11> after a the package restored with no error >  went to file>Build & Run > the project built and running successfully but when i tried to open the "MyScene.wescene" some exception occurred and prevent me from opening the scene 

here's the complete Log

>2020-12-18 02:09:19 [Debug] [WaveEngine.Runner.Game] Runner server started and waiting to load a project.
2020-12-18 02:09:19 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Opening project "C:\Users\Shadow\Documents\WaveEngineProjs\MyWaveProject\.waveengine\MyWaveProject.Windows\Build\bin"
2020-12-18 02:09:19 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project commands stream opened
2020-12-18 02:09:19 [Debug] [WaveEngine.Runner.Game] Registering and initializing WaveEngine services.
2020-12-18 02:09:21 [Information] [WaveEngine.Runner.Game] WaveEngine Game initialized
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "ProccessingAssetsCommand"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "ProccessingAssetsCommand"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "AssetsChanged"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Returning project assets
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command ("ViewerActivatedCommand") received
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "AssetsChanged"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "AssetsChanged"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "AssetsChanged"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "AssetsChanged"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "AssetsChanged"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "AssetsChanged"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Returning project assets
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "AssetsChanged"
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Returning project assets
2020-12-18 02:09:23 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Project command enqueued: "ProccessingAssetsCommand"
2020-12-18 02:09:33 [Verbose] [WaveEngine.Runner.Services.Server.ViewsEditorServer] Opening view '"581df1e0-cbbb-41dd-8c7f-c6afb01a1452"' for file '"C:\Users\Shadow\Documents\WaveEngineProjs\MyWaveProject\Content\Scenes\MyScene.wescene.wesc"'
2020-12-18 02:09:33 [Debug] [SerilogTraceListener.SerilogTraceListener] [142.00ms] Shader compiled id: df2ab68e-2005-4a33-af58-1f9bcf68fe27 pass: Default directives: 
2020-12-18 02:09:33 [Verbose] [WaveEngine.Runner.Services.Server.ViewsEditorServer] Generating containers for view: "581df1e0-cbbb-41dd-8c7f-c6afb01a1452"
2020-12-18 02:09:34 [Verbose] [WaveEngine.Runner.Services.Server.ViewsEditorServer] Containers generated for view : "581df1e0-cbbb-41dd-8c7f-c6afb01a1452"
2020-12-18 02:09:34 [Verbose] [WaveEngine.Runner.Services.Server.ViewsEditorServer] Containers generated for view : "581df1e0-cbbb-41dd-8c7f-c6afb01a1452"
2020-12-18 02:09:34 [Verbose] [WaveEngine.Runner.Services.Server.ViewsEditorServer] Surface for view "581df1e0-cbbb-41dd-8c7f-c6afb01a1452" updated
2020-12-18 02:09:34 [Error] [SerilogTraceListener.SerilogTraceListener] HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

>2020-12-18 02:09:34 [Debug] [SerilogTraceListener.SerilogTraceListener] [49.00ms] Shader compiled id: d551eb2b-202d-454d-a059-c3ddce284636 pass: Default directives: SUNDISK,MULTIVIEW
2020-12-18 02:09:34 [Error] [WaveEngine.Runner.Viewers.BaseAssetViewer] Exception in Draw loop of MyScene.wescene view. The scene draw has been paused.
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at SharpDX.Direct3D11.InputAssemblerStage.SetVertexBuffers(Int32 startSlot, Int32 numBuffers, IntPtr vertexBuffersOut, IntPtr stridesRef, IntPtr offsetsRef)
   at WaveEngine.DirectX11.DX11CommandBuffer.SetVertexBuffers(Buffer[] vertexBuffers, Int32[] offsets) in C:\agent\_work\5\s\src\Engine\Rendering\WaveEngine.DirectX11\DX11CommandBuffer.cs:line 314
   at WaveEngine.Framework.Graphics.MeshRenderUnit.Render(CommandBuffer commandBuffer, DrawContext drawContext, Int32 passId) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\MeshProcessors\Mesh\MeshRenderUnit.cs:line 88
   at WaveEngine.Framework.Graphics.DrawContext.RenderBatches(Int32 passId, CommandBuffer commandBuffer, Int32 count, Int32 offset) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\DrawContext.cs:line 424
   at WaveEngine.Framework.Graphics.DrawContext.RenderBatches(Int32 passId, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\DrawContext.cs:line 407
   at WaveEngine.Framework.Graphics.RenderPass.RenderBatches(DrawContext drawContext, CommandBuffer commandBuffer, RenderPassDescription& renderPassDescription) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\RenderPass.cs:line 98
   at WaveEngine.Framework.Graphics.ForwardDefaultPass.Render(DrawContext drawContext, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\Default\Forward\Passes\ForwardDefaultPass.cs:line 41
   at WaveEngine.Framework.Graphics.RenderPath.RenderPassesInternal(DrawContext drawContext, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\RenderPath.cs:line 126
   at WaveEngine.Framework.Graphics.CameraRenderPath.RenderPassesInternal(DrawContext drawContext, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\CameraRenderPath.cs:line 88
   at WaveEngine.Framework.Graphics.RenderPath.RenderPasses(DrawContext drawContext, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\RenderPath.cs:line 113
   at WaveEngine.Framework.Graphics.ForwardRenderPath.CameraRender(CameraDrawContext drawContext) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\Default\Forward\ForwardRenderPath.cs:line 101
   at WaveEngine.Framework.Graphics.CameraRenderPath.Render(DrawContext drawContext) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\CameraRenderPath.cs:line 38
   at WaveEngine.Framework.Graphics.CameraDrawContext.Render(TimeSpan gameTime) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\CameraDrawContext.cs:line 243
   at WaveEngine.Runner.Viewers.Scenes.Managers.EditorRenderManager.TryDrawContextRender(CameraDrawContext context, TimeSpan gameTime) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\Scenes\Managers\EditorRenderManager.cs:line 138
   at WaveEngine.Runner.Viewers.Scenes.Managers.EditorRenderPipeline.Render(TimeSpan gameTime) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\Scenes\Managers\EditorRenderPipeline.cs:line 27
   at WaveEngine.Framework.Managers.RenderManager.Draw(TimeSpan gameTime) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Managers\RenderManager.cs:line 220
   at WaveEngine.Framework.Managers.SceneManagers.DrawSceneManagers(TimeSpan gameTime) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Managers\SceneManagers.cs:line 690
   at WaveEngine.Framework.Scene.Draw(TimeSpan gameTime) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Scene.cs:line 538
   at WaveEngine.Runner.Viewers.BaseEditorScene.Draw(TimeSpan gameTime) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\BaseEditorScene.cs:line 161
   at WaveEngine.Runner.Viewers.BaseAssetViewer.Draw(TimeSpan gameTime) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\BaseAssetViewer.cs:line 242
2020-12-18 02:09:34 [Verbose] [WaveEngine.Runner.Services.Server.EditorServer] Returning project assets

**Comment by abo-github** [comment]
I've got the same problem here :-/ Can't figure out how to solve.

`
System.NullReferenceException
  HResult=0x80004003
  Nachricht = Object reference not set to an instance of an object.
  Quelle = WaveEngine.DirectX12
  Stapelüberwachung:
   at WaveEngine.DirectX12.DX12DescriptorAllocator..ctor(DX12GraphicsContext context, DescriptorHeapType heapType, UInt32 maxCount, DescriptorHeapFlags flags)
   at WaveEngine.DirectX12.DX12GraphicsContext.CreateDeviceInternal()
   at WaveEngine.Common.Graphics.GraphicsContext.CreateDevice(ValidationLayer validationLayer)
   at NET5Demo.Windows.DirectX12.Program.ConfigureGraphicsContext(Application application, Window window) in C:\Users\User\Desktop\NET5Demo-main\NET5Demo.Windows.DirectX12\Program.cs:line 52
`
