### ISSUE TITLE
Error on Draw Scene on Editor

### ISSUE THREAD

**Issue by lsfratel** [EvergineTeam/Feedback#71]
I just installed new version of WeveEngine 3.1 Preview 2. When I create a new project and i try to open my scene, the editor returns the following error:

`HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Parâmetro incorreto.
Exception in Draw loop of MyScene.wescene view. The scene draw has been paused.
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at SharpDX.Direct3D11.InputAssemblerStage.SetVertexBuffers(Int32 startSlot, Int32 numBuffers, IntPtr vertexBuffersOut, IntPtr stridesRef, IntPtr offsetsRef)
   at WaveEngine.DirectX11.DX11CommandBuffer.SetVertexBuffers(Buffer[] vertexBuffers, Int32[] offsets) in C:\agent\_work\5\s\src\Engine\Rendering\WaveEngine.DirectX11\DX11CommandBuffer.cs:line 314
   at WaveEngine.Framework.Graphics.MeshRenderUnit.Render(CommandBuffer commandBuffer, DrawContext drawContext, Int32 passId) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\MeshProcessors\Mesh\MeshRenderUnit.cs:line 88
   at WaveEngine.Framework.Graphics.DrawContext.RenderBatches(Int32 passId, CommandBuffer commandBuffer, Int32 count, Int32 offset) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\DrawContext.cs:line 424
   at WaveEngine.Framework.Graphics.DrawContext.RenderBatches(Int32 passId, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\DrawContext.cs:line 407
   at WaveEngine.Framework.Graphics.RenderPass.RenderBatches(DrawContext drawContext, CommandBuffer commandBuffer, RenderPassDescription& renderPassDescription) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\RenderPass.cs:line 98
   at WaveEngine.Framework.Graphics.ForwardDefaultPass.Render(DrawContext drawContext, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\Default\Forward\Passes\ForwardDefaultPass.cs:line 41
   at WaveEngine.Framework.Graphics.RenderPath.RenderPassesInternal(DrawContext drawContext, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\RenderPath.cs:line 126
   at WaveEngine.Framework.Graphics.CameraRenderPath.RenderPassesInternal(DrawContext drawContext, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\CameraRenderPath.cs:line 88
   at WaveEngine.Framework.Graphics.RenderPath.RenderPasses(DrawContext drawContext, CommandBuffer commandBuffer) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\RenderPath.cs:line 113
   at WaveEngine.Framework.Graphics.ForwardRenderPath.CameraRender(CameraDrawContext drawContext) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\Default\Forward\ForwardRenderPath.cs:line 101
   at WaveEngine.Framework.Graphics.CameraRenderPath.Render(DrawContext drawContext) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\CameraRenderPath.cs:line 38
   at WaveEngine.Framework.Graphics.CameraDrawContext.Render(TimeSpan gameTime) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\CameraDrawContext.cs:line 243
   at WaveEngine.Runner.Viewers.Scenes.Managers.EditorRenderManager.TryDrawContextRender(CameraDrawContext context, TimeSpan gameTime) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\Scenes\Managers\EditorRenderManager.cs:line 138
   at WaveEngine.Runner.Viewers.Scenes.Managers.EditorRenderPipeline.Render(TimeSpan gameTime) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\Scenes\Managers\EditorRenderPipeline.cs:line 27
   at WaveEngine.Framework.Managers.RenderManager.Draw(TimeSpan gameTime) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Managers\RenderManager.cs:line 220
   at WaveEngine.Framework.Managers.SceneManagers.DrawSceneManagers(TimeSpan gameTime) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Managers\SceneManagers.cs:line 690
   at WaveEngine.Framework.Scene.Draw(TimeSpan gameTime) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Scene.cs:line 538
   at WaveEngine.Runner.Viewers.BaseEditorScene.Draw(TimeSpan gameTime) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\BaseEditorScene.cs:line 161
   at WaveEngine.Runner.Viewers.BaseAssetViewer.Draw(TimeSpan gameTime) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\BaseAssetViewer.cs:line 242`

sorry, bad english.

**Comment by minolo** [comment]
Hello there!

Could you please tell us which graphics card you are using? Do you happen to have an NVIDIA Quadro?

Thanks!

**Comment by lsfratel** [comment]
Hi and no, is a old graphic card, gtx 650.

**Comment by emepetres** [comment]
@lsfratel I'm closing this as we are supporting now only Evergine. If you still have the issue, could you try latest Evergine version and check it out if the problem persists?

For quick resolution, check it out our [priority support](https://evergine.com/priority-support/)
