### ISSUE TITLE
DirectX 11 Rendering and Editor not supported on Windows7

### ISSUE THREAD

**Issue by TheRut** [EvergineTeam/Feedback#94]
Trying to run using DirectX 11 rendering results in the following error on Windows 7: 

System.EntryPointNotFoundException
  HResult=0x80131523
  Message=Unable to find an entry point named 'CreateDXGIFactory2' in DLL 'dxgi.dll'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Vortice.DXGI.DXGI.CreateDXGIFactory2_(Int32 _flags, Void* _riid, Void* _factoryOut)
   at Vortice.DXGI.DXGI.CreateDXGIFactory2(Int32 flags, Guid riid, IntPtr& factoryOut)
   at Vortice.DXGI.DXGI.CreateDXGIFactory2[T](Boolean debug)
   at WaveEngine.DirectX11.DX11GraphicsContext.CreateDeviceInternal()
   at WaveEngine.Common.Graphics.GraphicsContext.CreateDevice(ValidationLayer validationLayer)

This is due to DXGI 1.3 only being in Windows 8+.

It appears that the WaveEngine Editor by default uses DX, which means that while you CAN build and run WaveEngine games on Windows 7 as long as you use OpenGL rendering, you are unable to use the editor in any way.

There is no specific documentation stating the versions of Windows that WaveEngine officially supports, but given that Windows 7 is 16% of the Windows install base you might want to consider including it. This could be accomplished by either a) providing an option to use alternate renderers for the editor, or b) updating the DX renderer to use DXGI 1.2.

Thanks for listening!

**Comment by jcant0n** [comment]
Thank you for taking the time to report this issue. We are closing it due to extended inactivity. If you believe this issue is still relevant, please feel free to reopen it and we will be happy to revisit it. Thank you for your understanding and for helping us improve Evergine.
